services:
  - type: web
    name: hrms-lite-api
    env: python
    runtime: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGODB_URL
        value: mongodb+srv://rastogishubham216_db_user:Mt4B0HKDYXwMPs3T@clusterhrms.blkdkyw.mongodb.net/?retryWrites=true&w=majority&appName=Clusterhrms
      - key: DATABASE_NAME
        value: hrms_lite_db
      - key: PORT
        value: 10000